"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// layout
import { ThemeProvider } from "@/components/theme-provider";
import { SessionProvider } from "next-auth/react";
// import ClientLayout from "./ClientLayout";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
